import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { ReactNode } from "react";
import BackgroundImage from "../../components/BackgroundImage";
import Button from "../../components/Button";
import { getPage } from "../../lib/api";
import { Page } from "../../lib/schema";
import useMapImage from "../../utils/useMapImage";
import styles from "./../../styles/Services.module.css";


export default function Services(props: ReactNode & { page: Page }) {
    const router = useRouter();
    const { page } = props;
    const pageImages = useMapImage(page?.pageImgaesCollection?.items);

    return <div className={styles.servicesPage}>
        <Head>
            <title>{page.content.title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <BackgroundImage className={[styles.servicesContainer, styles.servicesContent]}
            url={pageImages[page.content.bgImageId]}
        >
            {React.Children.toArray(page.content.paragraphs?.map((x: any) => <p>{x}</p>))}
            <div className={styles.servicesNavigation}>
                {React.Children.toArray(page.content.buttons?.map((btn: any) => <Link
                    href={btn.link}
                >
                    <a>
                        <Button>
                            {btn.label}
                        </Button>
                    </a>
                </Link>
                ))}
            </div>

        </BackgroundImage>
    </div>
}

export async function getStaticProps() {
    const data = await getPage('/services');
    return {
        props: {
            page: data ?? null
        }
    }
}