import { faLinkedin } from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";
import Button from "../../components/Button";
import HeroImage from "../../components/HeroImage";
import InfoCard from "../../components/InfoCard";
import Label from "../../components/Label";
import styles from "./../../styles/About.module.css";

const infoCardDetails = [
    {
        name: 'Barry Ibell',
        imgUrl: '/images/road_landscape.jpg',
        designation: 'Founder & Managing Director',
        linkedIn: '',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris posuere interdum eros, sit amet aliquet sapien. Integer nec ipsum ac massa lobortis consectetur. Nulla lacinia rutrum turpis quis lacinia. Donec eget fermentum eros, non cursus odio.',
    },
    {
        name: 'Sarah-Jane Elston',
        imgUrl: '/images/road_landscape.jpg',
        designation: 'Co-Founder & Managing Director',
        linkedIn: '',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris posuere interdum eros, sit amet aliquet sapien. Integer nec ipsum ac massa lobortis consectetur. Nulla lacinia rutrum turpis quis lacinia. Donec eget fermentum eros, non cursus odio.',
    },
    {
        name: 'Milan Bulchandani',
        imgUrl: '/images/road_landscape.jpg',
        designation: 'Director - Sales & Marketing and Operation',
        linkedIn: '',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris posuere interdum eros, sit amet aliquet sapien. Integer nec ipsum ac massa lobortis consectetur. Nulla lacinia rutrum turpis quis lacinia. Donec eget fermentum eros, non cursus odio.',
    },
];
export default function About() {
    const router = useRouter();
    return (
        <div className={styles.about}>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.aboutContainer}>
                <HeroImage
                    src={'/images/road_landscape.jpg'}
                    height={291}
                    width={1365}
                    objectFit='cover'
                />
                <section className={styles.story}>
                    <Label>
                        Our Story
                    </Label>
                    <p>
                        Founded in 2022 by Barry Ibell and Sarah-Jane Elston,
                        Safer Driving Skills NZ (SDS NZ) is a full-service provider of
                        driver training programs for individuals and organizations in New Zealand.
                        <br />
                        <br />
                        Seeing the need of every road users, SDS NZ has established the company's mission
                        which is to raise awareness of safe driving habits so as to make the roads of
                        New Zealand the safest one for every road users.
                        <br />
                        <br />
                        Let's unite together and make this endeavor a success.
                    </p>
                </section>
                <section className={styles.apart}>
                    <Label>
                        What sets us apart
                    </Label>
                    <p>
                        With over 25 years of experience working as Driving Instructors and delivering training to all sort of drivers holding various classes of license, Barry and Sarah-Jane ensures the psychological methodology is applied with the needs of today's time. With this expertise we could effectively train drivers to the highest safety standards that we hold.
                        <br />
                        <br />
                        We understand how important the role of safe driving practices is, and keeping this in mind, we have carefully designed our training courses and formatted driver assessment structures so that we don't even fail to correct a simple mistake made by drivers.
                        <br />
                        <br />
                        This is just not a business for us, this is a huge responsibility towards making this nation full of safer drivers. Our experienced team of instructors walk along with time and are always updated with new changes taking place with respect to government policies, vehicles' technology and safe practices of driving. This is what makes us confident. We have always been and will always be fulfilling your requirements of driver training.
                    </p>
                </section>
                <section className={styles.infoContaienr}>
                    <Label>Who we are</Label>
                    <div className={styles.info}>
                        {React.Children.toArray(infoCardDetails.map(x => <InfoCard
                            {...x}
                        />)
                        )}
                    </div>
                </section>
                <section className={styles.services}>
                    <h3>
                        If you are looking for a knowledgeable as well as
                        motivated team that can help you or your staff in the
                        journey of being a safer driver,
                        connect with us using the link below.
                    </h3>
                    <h1>
                        Know more about our services.
                    </h1>
                    <Link
                        href={'/services'}
                    >
                        <a>
                            <Button>
                                Services
                            </Button>
                        </a>
                    </Link>
                </section>
            </main>
        </div>
    )
}