import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Card from '../components/Card'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.logo}>
          <Image
            src="/images/logo_1920x1920.png"
            width={700}
            height={700}
          />
        </div>
        <div className={styles.services}>
          <h1 className={styles.header}>
            Our Services
          </h1>
          <div className={styles.service_cards_wrapper}>
            <Card>
              <Link
                href="/"
              >
                <a>
                  <div className={styles.service_card}>
                    <Image
                      className={styles.card_image}
                      src="/images/individual.png"
                      height={500}
                      width={500}
                      objectFit='contain'
                    />
                    <h1>Individual</h1>
                  </div>
                </a>
              </Link>
            </Card>
            <Card>
              <Link
                href="/"
              >
                <a>
                  <div className={styles.service_card}>
                    <Image
                      className={styles.card_image}
                      src="/images/enterprise.png"
                      height={500}
                      width={500}
                      objectFit='contain'
                    />
                    <h1>Enterprise</h1>
                  </div>
                </a>
              </Link>
            </Card>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
